# Generated by Django 5.2.14 on 2026-05-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=255, null=True)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                ("nickname", models.CharField(blank=True, max_length=255, null=True)),
                ("hobbies", models.TextField(blank=True, null=True)),
                ("public_description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
